snapup/cart/urls.py
from django.urls import path
from . import views

app_name='cart'
urlpatterns = [

    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('remove/<int:product_id>/', views.cart_remove,name='cart_remove')

]

snapup/search/urls.py
from django.urls import path
from . import views

app_name='search'
urlpatterns = [

    path('',views.searchresult,name='searchresult'),
]

snapup/shop/urls.py
from django.urls import path

from . import views

app_name='shop'
urlpatterns = [

    path('',views.allProdCat,name='allProdCat'),
    path('<slug:c_slug>/',views.allProdCat,name='product_list_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.proDetail, name='prodCatDetail'),
]

snapup/snapup/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

from django.urls import path, include


urlpatterns =[
    path('admin/',admin.site.urls),
    path('search', include('search.urls')),
    path('cart/',include('cart.urls')),
    path('',include('shop.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

snapup/cart/models.py
from django.db import models

from shop.models import Product


class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)


class Cartitem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'Cartitem'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

snapup/search/models.py
from django.db import models

# Create your models here.

snapup/shop/models.py
from django.db import models


# Create your models here.
from django.urls import reverse


class Category(models.Model):
    name=models.CharField(max_length=300)
    slug=models.SlugField(max_length=100, unique=True)
    description=models.TextField()
    image=models.ImageField(upload_to='category', blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return '{}'.format(self.name)

    def get_url(self):
        return reverse('shop:product_list_by_category',args=[self.slug])



class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name=models.CharField(max_length=100, unique=True)
    slug=models.SlugField(max_length=100, unique=True)
    desc1=models.TextField()
    price=models.DecimalField(max_digits=7, decimal_places=2)
    img=models.ImageField(upload_to='product', blank=True)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('shop:prodCatDetail',args=[self.category.slug,self.slug])

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
        return self.name

snapup/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from shop.models import Product
from .models import Cart, Cartitem
from django.core.exceptions import ObjectDoesNotExist


# Create your views here.
def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            cart_id=_cart_id(request)
        )
        cart.save()
    try:
        cart_item = Cartitem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except Cartitem.DoesNotExist:
        cart_item = Cartitem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')


def cart_detail(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = Cartitem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity

    except ObjectDoesNotExist:
        pass
    return render(request, 'cart.html', dict(cart_items=cart_items, total=total, counter=counter))


def cart_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = Cartitem.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()

    else:
        cart_item.delete()
    return redirect('cart:cart_detail')

snapup/search/views.py
from django.shortcuts import render

from shop.models import Product
from django.db.models import Q


def searchresult(request):
    products: None
    query: None
    if 'q' in request.GET:
        query = request.GET.get('q')
        products = Product.objects.all().filter(Q(name__contains=query) | Q(desc1__contains=query))
        return render(request, 'search.html', {'query': query, 'productt': products})

snapup/shop/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404

# Create your views here.
from .models import Product, Category
from django.core.paginator import Paginator, EmptyPage, InvalidPage


# def index(request):
#     return render(request, 'index.html')

def allProdCat(request, c_slug=None):
    c_page = None
    products_list = None
    if c_slug != None:
        c_page = get_object_or_404(Category, slug=c_slug)
        products_list = Product.objects.all().filter(category=c_page, available=True)
    else:
        products_list = Product.objects.all().filter(available=True)
    paginator = Paginator(products_list, 6)
    try:
        page = int(request.GET.get('page', '1'))
    except:
        page = 1
    try:
        products = paginator.page(page)
    except (EmptyPage, InvalidPage):
        products = paginator.page(paginator.num_pages)

    return render(request, "category.html", {'category': c_page, 'product': products})


def proDetail(request, c_slug, product_slug):
    try:
        products = Product.objects.get(category__slug=c_slug, slug=product_slug)
    except Exception as e:
        raise e
    return render(request, 'product.html', {'product': products})

snapup/templates/cart.html
{% extends 'index.html' %}
{% load static %}
{% block metadescription %}
  this is the cart page
{% endblock %}
{% block title %}
  Cart ABC tech
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your Shopping Cart
        </h1>
        <br>
        <p class="text-center">
            Please Click <a href="{% url 'shop:allProdCat' %}">Here</a> to continue shopping
        </p>
    </div>
</div>

{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your shopping Cart
        </h1>
        <br>
    </div>
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
                <tr>
                    <th colspan="5">
                        Your Items

                    </th>

                </tr>

            </thead>
            <tbody>
            {% for cart_item in cart_items %}
            <tr>
                <td>
                    <a href="cart_item.product.get_absolute_url"><img src="{{cart_item.product.image.url}}" alt="" class="flot-left rounded custom image"></a>

                </td>
                <td class="text-left">
                    {{cart_item.product.name}}
                    <br>
                    P D : {{cart_item_product.id}}
                    <br>
                    Price: $ {{cart_item.product.price }}
                    <br>
                    Qty : {{cart_item.quantity}} x $ {{cart_item}}
                </td>
                <td>
                    $ {{cart_item.sub_total}}
                </td>
                {% if cart_item.quantity < cart_item.product.stock %}
                <td>
                    <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"> <i class="fa fa-plus custom_icon"> </i></a>
                    &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></i></a>
                    &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_icon"><i class="fa fa-trash custom_icon"></i></a>
                </td>
                {% else %}
                <td>
                    &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></i></a>
                    &nbsp;<a href="" class="custom_icon"><i class="fa fa-trash custom_icon"></i></a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
            </tbody>
        </table>
     </div>

<div class="col-12 col-md-12 col-lg-6 text-center">
    <table class="table my_custom_table_">

        <thead class="my_custom_thead">
        <th>
            CHECKOUT
        </th>
        </thead>
        <tbody>
        <tr>
            <td>
                Please review your shopping cart items before proceeding with payment
            </td>
        </tr>
        </tbody>
    </table>

<div class="mx-auto">
    <a href="{% url 'shop:allProdCat' %}" class="btn btn-secondary btn btn-secondary btn-block my_custom_button">Continue Shopping</a>
</div>
    {% endif %}

{% endblock %}

</div>
</div>
</div>

snapup/templates/category.html
{% extends 'index.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{category.description|truncatewords:150}}
    {% else %}
    welcome to abc store
    {% endif %}
{% endblock %}
{% block title %}
    {% if category %}
        {{category.name}}
    {% else %}
     Snap Up
    {% endif %}
{% endblock %}

{% block content %}

{% if category %}

<div>
     <div class="row my_class">
         <div class="mx-auto">
         <a class="btn btn-success"  href="{% url 'shop:allProdCat' %}"><b>Product collections</b></a>
     </div>
         </div>
 </div>
{% endif %}

<div class="mx-auto">

    <h1 class="text-center my_title">{{category.name}}</h1>
    <p class="text-justify">{{category.description}}</p>

    {% if category  %}

    <img class="my_image" src="{{category.image.url}}" alt="{{category.name}}" height="300;" width="850px;">

</div>
     <br>

     {% else %}
<div>
<img class="my_image my_image_padding" src="{% static 'img/banner.png' %}" alt="imgbanner"  width="1150px;">
</div>
<br>
<div>
    <h1 class="text-center my_title">Our products collections</h1>
    <p class="text-justify"> it is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>
</div>
      {% endif %}
<div class="container">
    <div class="row mx_auto">
        {% for pro in product %}
        <div class="my_bottom_margi col-9 col-sm-12 col-md-4 xol-lg-4">
             <div class="card text-center" style="min-width-18rem;">
                <a href="{{pro.get_url}}"><img class="card-img-top my_image" src="{{pro.img.url}}" alt="{{pro.name}}"></a>
             <div class="card-body">
                 <h4>{{pro.name}}</h4>
                  <p>${{pro.price}}</p>
             </div>
             </div>
        </div>
        {% endfor %}
    </div>
    <div class="mx-auto">

        <div class="text-center">
            {% for pg in product.paginator.page_range %}

               <a href="?page={{pg}}" class="btn btn-success btn-bg {% if product.number == pg %} active {% endif %}">{{pg}}</a>
            {% endfor %}

        </div>

    </div>

{% endblock %}

snapup/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">

    <p class="text-center">&copy; ABC tech private lmt.All rights reserved</p>

</div>

snapup/templates/header.html
{% load static %}
<header>
  <center>
    <div>
      <a href="{% url 'shop:allProdCat' %}"> <img src="{% static 'img/snapup.png' %}" alt="logo" width="319px;" height="216px;"></a>
    </div>
  </center>
</header>

snapup/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@1,300&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>

    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <title>{% block title %}{% endblock %}</title>

</head>
<body>


<div class="container">
{% include 'header.html' %}
{% include 'navbar.html' %}
{% block content %}
{% endblock %}
    </div>
{% include 'footer.html' %}
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>


</html>

snapup/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'shop:allProdCat' %}"><i class="fa fa-home"></i></a>
        </li>
        <li class="nav-item dropdown {% if 'shop' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          Category
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'shop:allProdCat' %}"></a></li>
             {% for cate in links %}
            <li><a class="dropdown-item" href="{{cate.get_url}}">{{cate.name}}</a></li>
            {% endfor %}
          </ul>
        </li>
        {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link " href="{% url 'cart:cart_detail' %}"><i class="fa fa-cart-plus"></i>({{item_count}})</a>
        </li>
        {% endif %}
      </ul>
      <form class="d-flex" action="{% url 'search:searchresult' %}" method="get">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class="fa fa-search"></i></button>
      </form>
    </div>
  </div>
</nav>

snapup/templates/product.html
{% extends 'index.html' %}
{% load static %}
{% block metadescription %}

        {{product.description|truncatewords:150}}
{% endblock %}
{% block title %}
    {% if category %}
        {{product.name}} - abc store

    {% endif %}
{% endblock %}

{% block content %}

<div class="row my_prod_row_class">
    <div class="mx_auto">
        <p> <a href="{% url 'shop:allProdCat' %}"> Home | <a href ="{{product.category.get_url}}">{{product.category}}</a>|<b>{{product.name}}</b></a></p>
    </div>
<div class="container">
<br>
<div class="row">
     <div class="col-12 col-sm-12 col-md-12 col-lg-3 text-center">
          <div style="min-width:18rem">
                <img src="{{product.img.url}}" alt="{{product.name}}">
          </div>
     </div>
     <div class="col-12 col-sm-12 col-md-12 col-lg-6">
         <div>
          <h2 class="my_prod_title"><b>{{product.name}}</b></h2>
          <p>${{product.price}}</p>
          <p class="my_title"><b>Product Description </b></p>
          <p class="text-justify my_prod_text">{{product.desc1}}</p>
          {% if product.stock <= 0 %}
          <p class="text-justify my_prod_text"><b>Out Of Stock</b></p>
          {% else %}
          <a class="btn btn-secondary" href="{% url 'cart:add_cart' product.id %}">Add To Cart</a>
          {% endif %}

         </div>

    </div>
</div>
</div>
</div>
{% endblock %}

snapup/templates/search.html
{% extends 'index.html' %}
{% load static %}
{% block metadescription %}
   we have different type of mobiles
{% endblock %}
{% block title %}
  Search
{% endblock %}
{% block content %}
<div>
    <p class="text-center my_search_text">you have search for :<b>"{{query}}"</b></p>
</div>
<div class="container">
    <div class="row mx_auto">
        {% for pro in productt %}
        <div class="my_bottom_margi col-9 col-sm-12 col-md-4 xol-lg-4">
             <div class="card text-center" style="min-width-18rem;">
                <a href="{{pro.get_url}}"><img class="card-img-top my_image" src="{{pro.img.url}}" alt="{{pro.name}}"></a>
             <div class="card-body">
                 <h4>{{pro.name}}</h4>
                  <p>${{pro.price}}</p>
             </div>
             </div>
            {% empty %}
            <div class="row mx-auto">
                <p class="text-center my_search_text"> 0 results found</p>
            </div>
          {% endfor %}
        </div>
    </div>
{% endblock %}